### ISSUE TITLE
Seed class

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#133]
Is source/Type/Seed.cpp still used ?

**Comment by Cylix** [comment]
Type::Seed::isValidSeed is used, maybe we can refactore it?

**Comment by thibault-martinez** [comment]
It's indeed the same function as `isValidTrytes(const Trytes& trytes)` from Trinary.cpp

**Comment by Cylix** [comment]
do you want to do the cleaning or me to do it?

**Comment by thibault-martinez** [comment]
I'll do it, thanks

**Comment by thibault-martinez** [comment]
c287163cd48b2a629386c6b03859e306d8fdd6b3
