### ISSUE TITLE
inspect reset

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#149]
For curl impl, we always called .reset before using sponge functions.
This is due to legacy code from java port.
However, I do believe this is unnecessary: it is 100% not necessary for curl, what about kerl?
If not, can we refactor to setup init in ctor or are we dependent from some external library behavior for the kerl impl?

**Comment by thibault-martinez** [comment]
.reset() is absolutely necessary for Kerl.
Removing it end up causing all associated tests to fail.

**Comment by Cylix** [comment]
can it be refactored to call reset in ctor or it may cause some issues?
I feel it is pretty poor OO design to have a ctor but still have to call an initialize function before being able to do anything with the object.
Otherwise, if it is not possible, just close this issue, that's a low priority stuff anyway.

**Comment by thibault-martinez** [comment]
Reset is actually called in ctor.

But you're right, I removed some useless call to .reset() in 3eefedea41764037010c044233ef79229a0527aa.

You are free to close this issue if that's ok for Curl too.
