### ISSUE TITLE
That API version actual yet?

### ISSUE THREAD

**Issue by PfAndrey** [thibault-martinez/iota.lib.cpp#157]
Hi. Sorry for my noobish question. 
Why the following simple snipped of code doesn't work properly?	

IOTA::API::Core api("node.iotawallet.info", 14265);
auto  res = api.getNodeInfo();
std::cout << res.getStatusCode() << std::endl;    //400 - bad request
std::cout << res.getError() << std::endl;              //Invalid API Version

**Comment by Cylix** [comment]
Hi,

Thanks for reporting this issue!

There was a recent release of the new stable API, v1.2.0.
The new API requires specifying a new header `X-IOTA-API-Version` set to the API version used. If it is not specified, a 400 error is returned.

This is now fixed.

Thanks again for reporting the issue and let us know if you encounter any other issues.

Best,
