### ISSUE TITLE
getAccountData

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#160]
getAccountData seriously needsome improvement.
I'm curious to see how performance differs between our lib and the java reference.

Please test with seed "IHDEENZYITYVYSPKAURUZAQKGVJEREFDJMYTANNXXGPZ9GJWTEOJJ9IPMXOGZNQLSNMFDSQOTZAEETUEA", it is endless.

**Comment by thibault-martinez** [comment]
For the record 

[Extended::getAccountData] getNewAddresses : 5102
    [Extended::getTransfers] getNewAddresses : 27964
    **[Extended::getTransfers] bundlesFromAddresses : 132547**
    [Extended::getTransfers] Total : 160511
[Extended::getAccountData] getTransfers : 160511
[Extended::getAccountData] getInputs : 25590
[Extended::getAccountData] Total : 191203

**Comment by thibault-martinez** [comment]
As seen in the screenshot, bundlesFromAddresses is taking 63% of the overall time, and the last loop of bundlesFromAddresses alone is taking 46% of the overall time.

![image](https://user-images.githubusercontent.com/3305068/34356284-cf37c280-ea3c-11e7-9c01-7e4ab4e3032d.png)

**Comment by thibault-martinez** [comment]
In https://github.com/thibault-martinez/iota.lib.cpp/pull/161, I introduce a parallel_for to speed up the loop.

As seen in the screenshot, the loop time and thus the overall time has been greatly reduced.

![image](https://user-images.githubusercontent.com/3305068/34357441-65c70f80-ea47-11e7-8504-4e3ad29a21aa.png)

**Comment by thibault-martinez** [comment]
However, getAccountData and all called functions still need to be optimised as the overall time is still too important.

**Comment by Cylix** [comment]
This is partially handled by #243.
I close this ticket as remaining part of the optimization is about bundleFromAddresses (#194).
