### ISSUE TITLE
Go through the TODOs in the code

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#184]

**Comment by Cylix** [comment]
probably create issues for each one and assign them to relevant milestone depending on priority.

**Comment by Cylix** [comment]
I went through the TODO.
I fixed the most trivial ones.

For the remaining ones, I listed them below.
For some, I am not sure of the intended action. For the other ones, I will create an issue and assign them to a more specific milestone.

- [ ] in FindTransactions `// TODO Don't really like that design, refactor it later.`. I guess Requests/Response design. I will extract that as an issue and we can think about it later
- [ ] in Service.hpp:90 `TODO set duration ?`. Not sure what this one is related to? The duration is extracted from the json response no?
- [ ]  in Extended.cpp, inside bundlesFromAddresses `  //! TODO: this will maybe re-query some tail transactions we already got (and we do filter that out in the next for loop) we maybe can filter the bundle list passed to findTransactionObjectsByBundle by restructuring the previous loop`. Will create issue for milestone 1.2.0.
- [ ] in Extended.cpp, prepareTransfer `// TODO Response ?`. This is related to the fact some API returns a Response object, while others return raw vectors. I will comment tickets related to API (usability) improvement.
- [ ] in CheckSum.cpp `// TODO add some checks + tests`. Will create/update appropriate issue.
- [ ] in pow.cpp, a simple TODO mark above the indices array (currently not used anywhere). May need your input @thibault-martinez on that. Also an todo concerning param names of loop. I won't create issue, leaving as-is for now.
- [ ] in crypto signing.cpp `// TODO optimize` for a loop in digest. Will create issue and assign to milestone 1.2.0.

**Comment by Cylix** [comment]
@thibault-martinez you can just leave me your input concerning the ones I didn't take any decision (whether we should do something or not). Then you can close this issue.

**Comment by thibault-martinez** [comment]
For the duration TODO, I think it was legacy from before deserialization was introduced, I'll remove it in an upcoming commit.

**Comment by thibault-martinez** [comment]
For the PoW box, I need to run some benchmark to see if using the indices array if more efficient than an if/else branch. I'll do that asap.

**Comment by thibault-martinez** [comment]
Last item (TODO in PoW) has been closed by be7f003e7feb70b4637ab98f53379326d8f74092.
I'm closing this issue.
