### ISSUE TITLE
CMake Error ExternalProject.cmake

### ISSUE THREAD

**Issue by CSPRNG** [thibault-martinez/iota.lib.cpp#207]
I followed your instructions and encountered an error message at the ..cmake step:

git clone --recursive git@github.com:thibault-martinez/iota.lib.cpp.git
cd iota.lib.cpp
mkdir build
cd build
cmake ..
make

Here are the errors output to terminal:

........./cmake/Modules/ExternalProject.cmake:2010 (message):
  No download info given for 'cpr_dep' and its source directory:

  ........./iota.lib.cpp/external/cpr

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * URL
   * GIT_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
   * SVN_REVISION
   * DOWNLOAD_COMMAND

Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.2/share/cmake/Modules/ExternalProject.cmake:2565 (_ep_add_download_command)
  cmake/cpr_settings.cmake:26 (ExternalProject_Add)
  CMakeLists.txt:86 (include)

-- Boost version: 1.65.1
-- Configuring incomplete, errors occurred!

**Comment by thibault-martinez** [comment]
Hi @CSPRNG,

Are you sure you used the `--recursive` option on git clone ?
This error typically appears when there are missing submodules.
You should try `git submodule update --init` after the clone.

Can you provide your cmake version too please ?

Cheers,

**Comment by CSPRNG** [comment]
Hi
You are correct, I forgot to use --recursive.
I cloned again from scratch, this time it failed during make , here is the outout at terminal:

[ 86%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/cyassl.c.o
[ 87%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/schannel.c.o
[ 87%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/darwinssl.c.o
[ 88%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/gskit.c.o
[ 89%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/mbedtls.c.o
[ 90%] Linking C shared library /iota.lib.cpp/deps/lib/libcurl.dylib
Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      _Curl_ossl_cleanup in openssl.c.o
      _Curl_ossl_close_all in openssl.c.o
  "_SSL_COMP_free_compression_methods", referenced from:
      _Curl_ossl_cleanup in openssl.c.o
  "_SSL_CTX_set_alpn_protos", referenced from:
      _ossl_connect_step1 in openssl.c.o
  "_SSL_CTX_set_next_proto_select_cb", referenced from:
      _ossl_connect_step1 in openssl.c.o
  "_SSL_get0_alpn_selected", referenced from:
      _ossl_connect_step2 in openssl.c.o
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [/iota.lib.cpp/deps/lib/libcurl.dylib] Error 1
make[4]: *** [opt/curl/lib/CMakeFiles/libcurl.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [cpr_dep-prefix/src/cpr_dep-stamp/cpr_dep-build] Error 2
make[1]: *** [CMakeFiles/cpr_dep.dir/all] Error 2
make: *** [all] Error 2

**Comment by thibault-martinez** [comment]
Thanks, I'm closing this issue and tagging you in a more appropriate one.
