### ISSUE TITLE
Address Appveyor & Travis CI warnings

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#209]
Could be interested to go through the compilation logs on each appveyor & travis builds and to address the possible existing warnings.

**Comment by thibault-martinez** [comment]
- [ ] test/source/api/core_test.cpp:94:38: warning: comparison of unsigned expression >= 0 is always true

**Comment by Cylix** [comment]
Now that AppVeyor is fully setup, I will have a look and clean the remaining one if any.
Waiting for build to complete.

**Comment by Cylix** [comment]
Done in 825f297d4b19fbe40dd398f6c86e5d2b20470479
