### ISSUE TITLE
Usable for embedded devices?

### ISSUE THREAD

**Issue by Citrullin** [thibault-martinez/iota.lib.cpp#223]
Hi, I got a simple question.
I tried the C Library and it seems like there are some issues. I need to figure out if I can fix it. 
Since this Library is way better maintained I would use this one. But I got one question: Can I use this Library on an embedded device without an underlying linux system? 

I'm currently using the ATMega328P for this purpose.

**Comment by Cylix** [comment]
Hi @Citrullin,

As of now, I can't answer precisely concerning this device or embedded devices in general.

We release the first stable version a bit less than 2 weeks ago and it was only targetting unix platforms.

The incoming release provides cross-platform on windows.

So, the current master branch guarantees it compiles and work on mac, linux or windows, but we do not have any tests o any embedded platforms for now.

However, it is in our plans to support ot and thus to guarantee it can be usable in good conditions on embedded devices.

Our current Roadmap is the following:

* v1.1.0: cross platform support, buildchain improvement and additional CI checks. Estimated release date is mid-february (by end of this week)
* v1.2.0: performance improvement. Estimated release date is mid-march. It may be earlier, but we prefer to allocate a whole month to have the time to profile the library and provide noticeable improvements.
* v2.0.0: embedded devices support. No estimated time for release.

So as you can see, even though we do not have any specific timeline to give you concerning the moment we will support embedded devices, you can see that we will start working on that around mid-march as it will be our main focus at that time.

Please let me know if you have any other questions you'd like me to answer.

I'm leaving this ticket open in case @thibault-martinez wants to add something :)

Best

**Comment by Citrullin** [comment]
@Cylix So that means: Just try it :D And fix it, if something breaks :) Okay, thanks.

**Comment by thibault-martinez** [comment]
Hi, nothing to add on my end, keep an eye on the library, it's definitely our goal to support embedded devices.

**Comment by Citrullin** [comment]
@thibault-martinez If you start with implementing, you can write me. We can figure out a nice to use solution. I think this will be probably complicated enough to support several different MCUs etc. :)

**Comment by thibault-martinez** [comment]
Sure, I will ! In the meantime, keep an eye on this [milestone](https://github.com/thibault-martinez/iota.lib.cpp/milestone/5), as it is our planned refactoring for embedded device.
