### ISSUE TITLE
Adapt CMake to build 32 or 64 bits library

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#228]

**Comment by Cylix** [comment]
For this one, what is the purpose/use case?

The user can already specify his own compiler / cross-compiler with `CXX` and possibly force 32/64 bits compilation using some compiler specific flags (like `-m32` or `-m64`). Those flags can be set using `CXX_FLAGS` in the cmake command line.

I can add some documentation in the wiki in the `compilation options` page if there is no specific use case. Can you update me on this @thibault-martinez?

**Comment by thibault-martinez** [comment]
Work was being done in https://github.com/thibault-martinez/iota.lib.cpp/commit/d735e96e7e8e8f1b977bdf8e7deda777800dbd9e

I ran into an error compiling 32 bits version in a 64 bits host.
Issue seemed to came from our cpr dependancy, I opened an issue 'https://github.com/whoshuu/cpr/issues/256)

**Comment by Cylix** [comment]
Found a way to bypass the curl version of cpr, will provide a fix.

**Comment by Cylix** [comment]
Having a try in 623c929e3f4ac51e37792e400ed06a0ce5601078
Will see how the CI goes.

Haven't tried yet with -m32 flag though, will try once CI is OK.
If everything works fine, I can also work on addnig a special 32 bits build on travis.

**Comment by Cylix** [comment]
#266
