### ISSUE TITLE
StopWatch test fail on rare case

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#238]
![image](https://user-images.githubusercontent.com/3305068/36533011-9d4c398c-17c2-11e8-9860-17eb8e432d96.png)

**Comment by thibault-martinez** [comment]
![image](https://user-images.githubusercontent.com/3305068/36727730-a2efe5a0-1bbe-11e8-9da4-920d2076f10f.png)

**Comment by Cylix** [comment]
Should be fixed by #247 now.
