### ISSUE TITLE
Fix test conflicts

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#240]
![image](https://user-images.githubusercontent.com/3305068/36567789-f501cdc6-1827-11e8-86d3-5718aa7e82a6.png)

**Comment by Cylix** [comment]
What's the reason for these failures? Is that on a development branch?

**Comment by thibault-martinez** [comment]
First of all, it does not appear on travis/appveyor, only on your local machine.
Reason is that some `storeTransactions` test are done with `BUNDLE_1_TRX_1_TRYTES` conflicting with other tests.
It appears if you run ctest twice.

**Comment by thibault-martinez** [comment]
Closed by #242
