### ISSUE TITLE
Add bundle finalization test to ensure that we don't sign normalized bundle with 13

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#262]

**Comment by Cylix** [comment]
@thibault-martinez I changed the test to check if we are currently testing the security flaw [here](https://github.com/thibault-martinez/iota.lib.cpp/commit/ba694de9b317aefa0207ca56b56325a04cc7e955).
Seems not: we may need to check with Chris for some testing data concerning that part.
