### ISSUE TITLE
Check if we are up to date with the API

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#283]
https://iota.readme.io/v1.3.0/reference#getnodeinfo

**Comment by Cylix** [comment]
Do you want me to take over some items on this ticket?

**Comment by thibault-martinez** [comment]
- I need to PR IRI to solve the 1st
- You can do 3rd

**Comment by thibault-martinez** [comment]
PR done and merged (https://github.com/iotaledger/iri/pull/776).
I'll update getBalances tonight.
