### ISSUE TITLE
isPromotable & checkConsistency

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#310]
From #304 (iota.lib.js changes):

```
isPromotable(tail) of develop branch is now renamed to checkConsistency(tail)
```
```
isPromotable(tail, depth) is now expressed as function of checkConsistency(tail) & depth, because promotion becomes ineffective after a few milestones. Internally uses a time heuristic: https://github.com/iotaledger/iota.lib.js/blob/next/packages/core/src/createIsPromotable.ts
```

Seems we have both isPromotable and checkConsistency, should we dismiss isPromotable?

**Comment by Cylix** [comment]
For this one, was a bit confused by the wording, but after investigation, seems that what we actually need to do is to support a new parameter `depth` for isPromotable.

The implementation can be found [here](https://github.com/iotaledger/iota.lib.js/blob/next/packages/core/src/createIsPromotable.ts).

**Comment by chrisdukakis** [comment]
Hey @Cylix & @thibault-martinez ,

most likely we are removing `isPromotable()` and  keep `checkConsistency()` without `depth` argument & `isAboveMaxDepth()` predicate.

I think IRI checks depth now:
https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/API.java#L461
https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java#L85

If I understand it correctly, pure `checkConsistency` as seen [here](https://github.com/chrisdukakis/iota.lib.js/blob/c128deab21b8c9e487e31423c5184290526f0d12/packages/core/src/createCheckConsistency.ts) is sufficient.
