### ISSUE TITLE
Investigate 0-balance with getAccountData

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#316]
Some users seem to be experiencing 0-balance using `getAccountData` 

@kuhlmannmarkus tagging you so that you see progress on this.
Also if you coud give some context for @Cylix that would be perfect, thanks.

**Comment by kuhlmannmarkus** [comment]
@thibault-martinez @Cylix sure thing. this is the snippet i used:
#include <iostream>
#include <iostream>
#include <iota/iota>

int main(){
  IOTA::API::Extended api("https://trinity.iota.fm", 443, true, 380);
  IOTA::Models::Seed seed("...", 2);
  auto res = api.getAccountData(seed);
  auto addr = res.getAddresses();
  for(unsigned int i =  0; i < addr.size(); i++){
    std::cout << "Address: " << addr.at(i).toTrytesWithChecksum () << std::endl;
    std::cout << "Balance: " << addr.at(i).getBalance ()  << std::endl;
  }
  return 0;
}


The balance on all addresses is always shown to be zero. I double checked the addresses with thetangle.org and with CLI commands and also used different nodes. Non-zero balance should be shown.


I have now used the "Extended" object to retrieve "accountData" and then extracted the balances with a "Core" object:

IOTA::API::Core api2("https://trinity.iota.fm", 443, true, 380);
auto bals = api2.getBalances(addr).getBalances();

This works as expected, though

**Comment by Cylix** [comment]
I could indeed reproduce, will investigate.
Thanks for reporting this issue!
