### ISSUE TITLE
Fail at running test in run_build.sh

### ISSUE THREAD

**Issue by HowJMay** [thibault-martinez/iota.lib.cpp#319]
OS: Ubuntu 16.04 LTS
I ran the run_build.sh in iota.lib.cpp after I ran the iri_setup.sh
Did I miss something or do something wrong?

Thank you
here is the result [run_build.sh result](https://gist.github.com/HowJMay/44f438a5dd3a4e65a7bd8f3015988678)
`         1 - extended_get_bundle_test (Failed)
	  2 - extended_bundles_from_addresses_test (Failed)
	  3 - extended_get_balances_and_format_test (Failed)
	  4 - extended_initiate_transfer_test (Failed)
	  5 - extended_get_account_data_test (Failed)
	  6 - extended_replay_bundle_test (Failed)
	  7 - extended_get_inputs_test (Failed)
	  8 - extended_send_transfer_test (Failed)
	  9 - extended_get_new_addresses_test (SEGFAULT)
	 10 - extended_add_remainder_test (Failed)
	 11 - extended_broadcast_and_store_test (Failed)
	 12 - extended_get_transfers_test (Failed)
	 13 - extended_find_transactions_test (Failed)
	 14 - extended_traverse_bundle_test (Failed)
	 15 - extended_find_transaction_objects_test (Failed)
	 16 - extended_find_transaction_objects_by_bundle_test (Failed)
	 17 - extended_prepare_transfers_test (Failed)
	 18 - extended_get_transactions_objects_test (Failed)
	 19 - extended_is_reattachable_test (Failed)
	 20 - extended_is_promotable_test (Failed)
	 21 - extended_get_latest_inclusion_test (Failed)
	 22 - extended_send_trytes_test (Failed)
	 40 - core_attach_to_tangle_test (Failed)
	 41 - core_broadcast_transactions_test (Failed)
	 43 - core_store_transactions_test (Failed)
	 44 - core_get_inclusions_states_test (Failed)
	 45 - core_get_trytes_test (Failed)
	 46 - core_get_transactions_to_approve_test (Failed)
	 47 - core_were_addresses_spent_from_test (Failed)
	 48 - core_find_transactions_test (Failed)
	 50 - core_get_balances_test (Failed)
	 51 - core_check_consistency_test (Failed)
	 88 - crypto_pow_test (Failed)
	 89 - crypto_multi_signing_test (Failed)
`

[iri_setup.sh_1](https://gist.github.com/HowJMay/b4f15234f1669342c573c68fee362945)
`Cloning into 'test/testnet/iri'...
remote: Counting objects: 18931, done.
remote: Total 18931 (delta 0), reused 0 (delta 0), pack-reused 18930
Receiving objects: 100% (18931/18931), 98.30 MiB | 3.49 MiB/s, done.
Resolving deltas: 100% (8180/8180), done.
Checking connectivity... done.
Note: checking out '937cb404'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 937cb40... Merge branch 'release-v1.5.0' into dev
cp: cannot stat './iri_config/Snapshot.txt': No such file or directory
cp: cannot stat './iri_config/iri.ini': No such file or directory`
[iri_setup.sh_2](https://gist.github.com/HowJMay/191c753b9fa43daef6946a93aa96b935)
`07/26 14:39:19.997 [main] ERROR com.iota.iri.Snapshot - Failed to load snapshot. 
   java.io.FileNotFoundException: src/main/resources/Snapshot.txt (No such file or directory)
at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_171]
at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_171]
at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_171]
at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_171]
at com.iota.iri.Snapshot.getSnapshotStream(Snapshot.java:51) [iri-1.5.0.jar:na]
at com.iota.iri.Snapshot.initInitialState(Snapshot.java:77) [iri-1.5.0.jar:na]
at com.iota.iri.Snapshot.init(Snapshot.java:38) [iri-1.5.0.jar:na]
at com.iota.iri.Iota.<init>(Iota.java:64) [iri-1.5.0.jar:na]
at com.iota.iri.IRI$IRILauncher.main(IRI.java:78) [iri-1.5.0.jar:na]
at com.iota.iri.IRI.main(IRI.java:32) [iri-1.5.0.jar:na]
`

**Comment by Cylix** [comment]
Hi @HowJMay,

From the logs:
```
cp: cannot stat './iri_config/Snapshot.txt': No such file or directory
cp: cannot stat './iri_config/iri.ini': No such file or directory
```

it seems the script failed to copy the Snapshot and the iri configuration file.
It should also copy our database to make sure the tests pass.

Here is how to fix the installation.
For the ease of the explanation, let's say that:
* `LIBRARY_PATH` is the path to your `iota.lib.cpp` repository
* `IRI_PATH` is the path to the `iri` repository

```
cd IRI_PATH
rm -rf testnetdb*
cp -r LIBRARY_PATH/test/testnet/testnetdb .
cp LIBRARY_PATH/test/testnet/iri_config/Snapshot.txt src/main/resources
cp LIBRARY_PATH/test/testnet/iri_config/iri.ini .
```

You will need to rebuild iri (`mvn clean compile && mvn package`).
Then, you should be able to start iri correctly and run the tests.

Please let me know if you need further assistance.

Best

**Comment by HowJMay** [comment]
Thank you. I am going to try now
