### ISSUE TITLE
Keccak dependency

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#70]

**Comment by Cylix** [comment]
Done in 1b79c7d67b030519388b20087ffc68e4032a851e

Linux and Mac are fully using it as a dependency using the provided Makefile.
For windows, the Makefile cannot be integrated with our buildchain. As an alternative, we integrate the relevant source files to our build.

I raised an issue to ask about the possible CMake integration.
Whenever this library will support CMake, we will be able to improve this current implementation.

For reference: https://github.com/gvanas/KeccakCodePackage/issues/39
