### ISSUE TITLE
Proof of work

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#78]

**Comment by Cylix** [comment]
pow is implemented, additional testing will be done for 1.0.0 (stable).
I'm keeping open but I switch the milestone.

**Comment by thibault-martinez** [comment]
I'm adding multi-threaded pow to the scope of this issue.

**Comment by thibault-martinez** [comment]
Multithreaded PoW was added in 87c85962bf29f784d01e0c7d03dc81822e6b545a.
Still needs to be tested more.

**Comment by thibault-martinez** [comment]
Pow was refactored in ca190b77c52bb6b3b61653a6490dabea14d45291

**Comment by thibault-martinez** [comment]
Closed by 4cc04dadc86d120234c74a3c6235a4a1f11f1c48
