### ISSUE TITLE
includes with angle brackets & full path

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#83]

**Comment by thibault-martinez** [comment]
Seems like @eroween has a different point of view on that.
Can we discuss it here ?

**Comment by Cylix** [comment]
Hey @eroween,

From my own experience, angle-brackets includes are necessary for libraries intetended to be used and installed by other people, as well as specifying the full path (by full path, I mean the path starting from the include directory).

I used to set my includes with quotes, but I had to change.
The reason behind this is that some users of libraries I developed installed the library goobally on the system and then included specifics headers. However, these headers were including quoted includes, and somehow it broke on some systems (leading the compiler not being able to find those includes).

Many other libraries use that design too (for example boost asio).

One may argue that this is not expected to have system headers to include your own library files, but environment, compilers, ... are really different from one machine to another that it is difficult to stick to the theoretical best practices. Taking deployment on unknown environment in consideration is sometimes pretty trick.

Would you mind share your concerns concernig this design?

**Comment by eroween** [comment]
Hey @Cylix 

For a header only library, it can make sense to only use system include, but for compiled libraries using quote allows the compiler to issue warnings for the included headers.

Each boost/std header are meant to be used alone, which is not the same on a compiled library.

OpenCV is based on this principle, same as others widely distributed library (CryEngine/spdlog/imgui/catch/llvm...)

**Comment by thibault-martinez** [comment]
What's the status of this issue ?

**Comment by Cylix** [comment]
I doubled check right now, seems like we got angles everywhere, this can be closed.
