### ISSUE TITLE
Check types

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#92]

**Comment by Cylix** [comment]
Does that issue include type consistency (like std::string and Type::Trytes) or should we create another issue for that purpose?

**Comment by thibault-martinez** [comment]
It was indeed 100% aimed to Type::Trytes.

**Comment by thibault-martinez** [comment]
Closed by af1c5ba9fb3840a8a878253fb33f84477e79188a
