### ISSUE TITLE
Fix CMake Policy CMP0048

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#93]

**Comment by Cylix** [comment]
Nothing we can do on our side.

If we force set the policy, it is reset by the min_version directive of the CPR project CMakelist.
Another alternative would be to switch to externalproject_add, but that would be weird to have some project with add_subdirectory and some with externalproject_add.

I submitted a PR on the vendor library from which the warning comes from: https://github.com/whoshuu/cpr/pull/221

Let's hope it is merged!

**Comment by Cylix** [comment]
d90f646f9594fc10a66be5a76fd57fedb27bd211
