### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#99]

**Comment by thibault-martinez** [comment]
Switch from .com to .org done

**Comment by thibault-martinez** [comment]
7655cc9227011c44cdaf8b963478739253588835 fixed submodules issue

**Comment by thibault-martinez** [comment]
Still need to setup boost in [.travis.yml](https://github.com/thibault-martinez/iota.lib.cpp/blob/master/.travis.yml)

**Comment by Cylix** [comment]
fixed in #127
